<template>
  <div class="case-details">
    <div class="report-actions no-print">
      <button @click="isReportMode = !isReportMode" class="report-btn no-print">
        {{ isReportMode ? ' < Back to Tabs' : 'View as Report' }}
      </button>
      <div v-if="isReportMode">
        <button @click="printReport" class="print-btn no-print">
          <Icon icon="line-md:download" class="search-icon"/>
          Print / Save as PDF
        </button>
      </div>
    </div>

    <div :class="{ 'a4-layout': isReportMode }">
      
      <div v-if="isReportMode" class="report-header">
        <div class="report-meta-top">
          <span class="meta-status">{{ caseData.status }}</span>
          <span class="meta-risk" :class="`risk-${caseData.severity_id}`">
            {{ caseData.severity_id === 1 ? 'High Risk' : caseData.severity_id === 2 ? 'Medium Risk' : 'Low Risk' }}
          </span>
        </div>
        <h1 class="school-title">{{ caseData.school_name }}</h1>
        <p class="school-address">
          {{ caseData.school_address || 'School Address Not Available' }}
        </p>
        <hr class="header-divider" />
      </div>

      <h2>Student Child Protection Report</h2>

      <div v-if="!isReportMode" class="header-row">
        <div class="case-type-group">
          <span
            v-for="type in allCaseTypes"
            :key="type.id"
            class="case-type-chip"
            :class="{ active: caseData.case_type_id === type.id }"
          >{{ type.name }}</span>
        </div>

        <div class="status-info">
          <router-link v-if="caseData.student_id && (accessLevel === 1 || accessLevel === 2 || accessLevel === 3)" :to="{name: 'Student', params: {student: caseData.student_id}}" class="link">View Student History</router-link>
          <span class="status-pill" :class="statusPillClass">{{ caseData.status }}</span>
          <button v-if="accessLevel === 1 || accessLevel === 2 || accessLevel === 3" @click="openStatusModal" class="update-status-btn">
            Update Status
          </button>
        </div>
      </div>

      <div
        v-if="!isReportMode && statusInfo && (caseData.status === 'On Hold' || caseData.status === 'Resolved')"
        class="status-extra-info"
        :style="{ borderLeftColor: caseData.status === 'On Hold' ? '#b20000' : '#1e3a8a' }"
      >
        <p><strong>{{ caseData.status === 'On Hold' ? 'On Hold Since' : 'Date Resolved' }}:</strong> {{ formatDate(statusInfo.changed_date) }}</p>
        <p v-if="statusInfo.comment"><strong>{{ caseData.status === 'On Hold' ? 'Reason' : 'Comment' }}:</strong> {{ statusInfo.comment }}</p>
      </div>

      <div v-if="!isReportMode" class="share-with">
        <span><Icon icon="line-md:account"></Icon> Shared with:</span>
        <span v-for="user in caseData.sharedUsers" :key="user.id" class="share-chip">
          {{ user.name }}
        </span>
      </div>

      <div class="tabs no-print" v-if="!isReportMode">
        <button class="tab" :class="{ active: activeTab === 'personal' }" @click="activeTab = 'personal'">
          Personal Information
        </button>
        <button class="tab" :class="{ active: activeTab === 'report' }" @click="activeTab = 'report'">
          Report Details
        </button>
      </div>

      <div class="tab-content" :class="{ 'report-document-layout': isReportMode }">
        
        <div class="doc-section" v-show="isReportMode">
          <h3 class="section-title">I. Submission Details</h3>
          <div class="doc-grid cols-2">
            <div class="data-cell"><span class="label">Case Type:</span><span class="val">{{ allCaseTypes.find(type => type.id === caseData.case_type_id)?.name || 'N/A' }}</span></div>
            <div class="data-cell"><span class="label">Status:</span><span class="val">{{ caseData.status }}</span></div>
            <div class="data-cell"><span class="label">Submitted on:</span><span class="val">{{ formatDate(caseData.created_at) }}</span></div>
            <div class="data-cell"><span class="label">Generated by:</span><span class="val">{{ caseData.created_by_name || 'N/A' }}</span></div>
          </div>
          <div class="data-cell full-width mt-1">
            <span class="label">Shared with:</span>
            <span class="val">
              {{ caseData.sharedUsers?.map(u => u.name).join(', ') || 'None' }}
            </span>
          </div>
        </div>

        <div class="doc-section" v-show="activeTab === 'personal' || isReportMode">
          <h3 class="section-title" v-if="isReportMode">II. Student Information</h3>
          
          <div class="personal-info" v-if="!isReportMode">
            <div class="info-row">
              <div><strong>School</strong><p>{{ caseData.school_name }}</p></div>
              <div><strong>Student Status - Duration of Stay</strong><p><span class="pill">{{ caseData.studentStatus || 'N/A'}}</span></p></div>
            </div>
            <div class="info-row">
              <div><strong>Name</strong><p>{{ caseData.first_name }} {{ caseData.last_name }}</p></div>
              <div><strong>Nickname</strong><p>{{ caseData.nickname }}</p></div>
            </div>
            <div class="info-row">
              <div><strong>Nationality</strong><p>{{ caseData.nationality_name }}</p></div>
              <div><strong>Cohort</strong><p>{{ caseData.cohort_name }}</p></div>
            </div>
          </div>

          <div class="doc-grid cols-2" v-else>
            <div class="data-cell"><span class="label">Name:</span><span class="val">{{ caseData.first_name }} {{ caseData.last_name }}</span></div>
            <div class="data-cell"><span class="label">Nickname:</span><span class="val">{{ caseData.nickname || 'N/A' }}</span></div>
            <div class="data-cell"><span class="label">School:</span><span class="val">{{ caseData.school_name }}</span></div>
            <div class="data-cell"><span class="label">Student Status:</span><span class="val">{{ caseData.studentStatus || 'N/A' }}</span></div>
            <div class="data-cell"><span class="label">Nationality:</span><span class="val">{{ caseData.nationality_name || 'N/A' }}</span></div>
            <div class="data-cell"><span class="label">Cohort:</span><span class="val">{{ caseData.cohort_name || 'N/A' }}</span></div>
          </div>
        </div>

        <div class="doc-section" v-show="activeTab === 'report' || isReportMode">
          <h3 class="section-title" v-if="isReportMode">III. Report Details</h3>
          <h3 v-else>Report Details</h3>

          <div class="report-info" v-if="!isReportMode">
            <div class="info-row">
              <div class="info-block">
                <strong>Category</strong>
                <p>{{ caseData.category_name }}</p>
              </div>
              <div class="info-block">
                <strong>Severity</strong>
                <div class="severity-tags">
                  <span class="severity" :class="{ active: caseData.severity_id === 1 }">High</span>
                  <span class="severity" :class="{ active: caseData.severity_id === 2 }">Medium</span>
                  <span class="severity" :class="{ active: caseData.severity_id === 3 }">Low</span>
                </div>
              </div>
            </div>

            <div class="info-block">
              <strong>Specifications</strong>
              <div class="spec-tags">
                <span v-for="(spec, index) in caseData.subcategories" :key="index" class="spec-chip">
                  {{ spec.name }}
                </span>
              </div>
            </div>

            <div class="info-block">
              <strong>Reason</strong>
              <textarea class="reason-box" readonly rows="5">{{ caseData.reason }}</textarea>
            </div>
          </div>

          <div class="doc-report-details" v-else>
            <div class="data-cell full-width mb-2">
              <span class="label">Category:</span>
              <span class="val">{{ caseData.category_name }}</span>
            </div>
            <div class="data-cell full-width mb-2">
              <span class="label">Specification(s):</span>
              <span class="val">
                {{ caseData.subcategories?.map(s => s.name).join(', ') || 'None' }}
              </span>
            </div>
            <div class="data-block mb-3">
              <div class="label pb-1">Reason(s):</div>
              <div class="val report-text-block">{{ caseData.reason }}</div>
            </div>
          </div>

          <div class="info-block mt-3" :class="{ 'doc-block-clean': isReportMode }">
            <strong v-if="!isReportMode">Media & Documentation</strong>
            <div v-if="isReportMode && caseData.uploadedFiles?.length" class="label pb-1">Media & Documentation:</div>
            
            <div v-if="caseData.uploadedFiles?.length" class="media-grid-wrapper">
              <div class="media-grid">
                <div v-for="(file, index) in caseData.uploadedFiles" :key="index" class="media-card">
                  <img v-if="isImage(file.file_url)" :src="file.file_url" class="media-preview" @click="openImage(file.file_url)" />
                  <video v-else-if="isVideo(file.file_url)" controls class="media-preview">
                    <source :src="file.file_url"/>
                  </video>
                  <div v-else class="document-preview"><Icon icon="line-md:document"/></div>
                </div>
              </div>
            </div>
            <p v-else-if="!isReportMode" class="no-files">No media files attached.</p>
          </div>

          <div class="info-block" :class="{ 'doc-block-clean': isReportMode, 'mt-4': isReportMode }">
            <strong v-if="!isReportMode">Privacy Policy Acknowledgment</strong>
            <div class="privacy-checkbox-wrapper">
              <label class="privacy-label-clean">
                <input type="checkbox" :checked="caseData.privacy_policy_acknowledged" disabled class="doc-checkbox" />
                I acknowledge that I have read and understood the Privacy Policy.
              </label>
            </div>
            <p v-if="caseData.privacy_policy_acknowledged_at" class="privacy-date">
              Acknowledged on: {{ formatDateTime(caseData.privacy_policy_acknowledged_at) }}
            </p>
          </div>
        </div>

      </div>
    </div>

    <div v-if="showStatusModal" class="modal-overlay" @click.self="handleCloseStatusModal">
      <div class="status-modal">
        <h3>Update Case Status</h3>
        <div class="modal-current-status">
          Current status: <span class="status-pill" :class="statusPillClass">{{ caseData.status }}</span>
        </div>
        <div class="form-group">
          <label>New Status <span class="required">*</span></label>
          <select v-model="newStatus" class="form-select">
            <option value="">Select a status</option>
            <option v-for="option in statusOptions.filter(o => o !== caseData.status)" :key="option" :value="option">
              {{ option }}
            </option>
          </select>
        </div>
        <div class="form-group">
          <label>Date Changed <span class="required">*</span></label>
          <input type="date" v-model="statusChangeDate" class="form-input" :max="todayDate" />
        </div>
        <div class="form-group">
          <label>Reason / Comment <span v-if="newStatus.toLowerCase() === 'on hold'" class="required"> *</span><span v-else class="optional"> (optional)</span></label>
          <textarea v-model="statusComment" class="form-textarea" rows="4" placeholder="Enter reason or comment..."></textarea>
        </div>
        <div v-if="statusModalError" class="modal-error">{{ statusModalError }}</div>
        <div class="modal-actions">
          <button @click="handleCloseStatusModal" class="btn-cancel">Cancel</button>
          <button @click="submitStatusUpdate" class="btn-submit" :disabled="submittingStatus">
            {{ submittingStatus ? 'Updating...' : 'Update Status' }}
          </button>
        </div>
      </div>
    </div>

    <ConfirmModal
      v-model="showDiscardStatusConfirm"
      title="Discard status update?"
      message="You have unsaved changes to this case's status. Are you sure you want to discard them?"
      confirm-text="Yes, discard"
      cancel-text="No, keep editing"
      variant="danger"
      @confirm="closeStatusModal"
    />

    <transition name="fade">
      <div v-if="toast.show" class="toast" :class="`toast-${toast.type}`">
        <Icon icon="line-md:alert-circle-loop" class="icon"/>
        {{ toast.message }}
        <Icon icon="line-md:close" class="close-icon" @click="closeToast"/>      
      </div>
    </transition>
  </div>
</template>

<script setup lang="ts">
/* Script setups remains completely identical to your original engine */
import { ref, onMounted, computed } from 'vue';
import { useRoute } from 'vue-router';
import api from '../services/api';
import { Icon } from '@iconify/vue';
import ConfirmModal from '../components/common/ConfirmModal.vue';

const route = useRoute();
const activeTab = ref<'personal' | 'report'>('personal');
const statusOptions = ref(['In Progress', 'On Hold', 'Resolved'])
const allCaseTypes = ref<any[]>([]);
const accessLevel = ref(0);
const isReportMode = ref(false);
const selectedImage = ref('');
const showImageModal = ref(false);

const openImage = (imageUrl: string) => {
  selectedImage.value = imageUrl;
  showImageModal.value = true;
};
const closeImage = () => {
  showImageModal.value = false;
  selectedImage.value = '';
};

const caseData = ref<any>({
  childProtectionConcern: false,
  counsellingConcern: false,
  sharedUsers: [],
  studentStatus:'',
  selectedCounselors: [],
  school_name: '',
  school_address: '',
  enrollmentDate: '',
  first_name: '',
  last_name: '',
  nickname: '',
  nationality_name: '',
  cohort_name: '',
  category_name: '',
  severity_id: '',
  specifications: [],
  reason: '',
  uploadedFiles: []
});

const fetchCaseData = async (caseId: number) => {
  try {
    const { data } = await api.get(`/cases/${caseId}`);
    const normalized = statusOptions.value.find(opt => opt.toLowerCase() === data.status.toLowerCase());
    data.status = normalized || '';
    data.sharedUsers = data.sharedUsers || [];
    caseData.value = data;
  } catch (err) {
    console.error('Failed to fetch case data', err);
  }
};

const fetchAllCaseTypes = async() => {
  try {
    const { data } = await api.get('/cases/case-types');
    allCaseTypes.value = data;
  } catch (err) {
    console.error('Failed to fetch case types', err);
  }
};

const statusInfo = ref<any>(null);
const fetchStatusInfo = async (caseId: number) => {
  try {
    const { data } = await api.get(`/cases/${caseId}/status-history`);
    if (data.length > 0) {
      const latest = data[0];
      if (latest.new_status.toLowerCase() === caseData.value.status?.toLowerCase()) {
        statusInfo.value = latest;
      } else {
        statusInfo.value = null;
      }
    } else {
      statusInfo.value = null;
    }
  } catch (err) {
    console.error('Failed to fetch status history', err);
  }
};

const formatDate = (dateStr: string) => {
  if (!dateStr) return '';
  const [year, month, day] = dateStr.split('T')[0].split('-');
  return new Date(parseInt(year), parseInt(month) - 1, parseInt(day))
    .toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
};

const showStatusModal = ref(false);
const newStatus = ref('');
const statusChangeDate = ref('');
const statusComment = ref('');
const statusModalError = ref('');
const submittingStatus = ref(false);
const todayDate = new Date().toISOString().split('T')[0];

const statusPillClass = computed(() => {
  const s = caseData.value.status?.toLowerCase() ?? '';
  if (s === 'in progress') return 'status-in-progress';
  if (s === 'on hold') return 'status-on-hold';
  if (s === 'resolved') return 'status-resolved';
  return '';
});

const openStatusModal = () => {
  newStatus.value = '';
  statusChangeDate.value = todayDate;
  statusComment.value = '';
  statusModalError.value = '';
  showStatusModal.value = true;
};
const closeStatusModal = () => { showStatusModal.value = false; };
const showDiscardStatusConfirm = ref(false);
const handleCloseStatusModal = () => {
  if (newStatus.value || statusComment.value.trim()) {
    showDiscardStatusConfirm.value = true;
  } else {
    closeStatusModal();
  }
};

const submitStatusUpdate = async () => {
  if (!newStatus.value) {
    statusModalError.value = 'Please select a new status.';
    return;
  }
  if (newStatus.value.toLowerCase() === 'on hold' && !statusComment.value.trim()) {
    statusModalError.value = 'A reason is required when setting status to On Hold.';
    return;
  }
  submittingStatus.value = true;
  statusModalError.value = '';
  try {
    await api.patch(`/cases/${caseData.value.id}`, {
      status: newStatus.value,
      changed_date: statusChangeDate.value,
      comment: statusComment.value || null
    });
    const normalized = statusOptions.value.find(opt => opt.toLowerCase() === newStatus.value.toLowerCase());
    caseData.value.status = normalized || newStatus.value;
    closeStatusModal();
    fetchStatusInfo(caseData.value.id);
    showToast('Status updated successfully', 'success');
  } catch (err: any) {
    statusModalError.value = err.response?.data?.message || 'Failed to update status.';
  } finally {
    submittingStatus.value = false;
  }
};

onMounted(async() => {
  try {
    const res = await api.get('users/me');
    accessLevel.value = res.data.access_level;
    const caseId = route.params.caseId;
    if(caseId && !isNaN(Number(caseId))) {
      await fetchCaseData(Number(caseId));
      fetchAllCaseTypes();
      fetchStatusInfo(Number(caseId));
    }
  } catch (err) {
    console.error('Failed to fetch data', err);
  }
});

const toast = ref({ show: false, message: '', type: 'success' as 'success' | 'error' });
const showToast = (message: string, type: 'success' | 'error') => {
  toast.value.message = message;
  toast.value.type = type;
  toast.value.show = true;
  setTimeout(() => { toast.value.show = false; }, 4000);
};
const closeToast = () => { toast.value.show = false; };

const printReport = async () => {
  isReportMode.value = true;
  await new Promise(resolve => setTimeout(resolve, 300));
  window.print();
};

const isImage = (file: string) => /\.(jpg|jpeg|png|gif|bmp|webp)$/i.test(file);
const isVideo = (file: string) => /\.(mp4|webm|ogg)$/i.test(file);
const getFileName = (filePath: string) => filePath.split('/').pop() || 'file';
const formatDateTime = (dateStr: string) => {
  if (!dateStr) return '';
  return new Date(dateStr).toLocaleString('en-GB', {
    day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit'
  });
};
</script>

<style scoped>
/* ==========================================================================
   APP CONTAINER BASICS
   ========================================================================== */
.case-details {
  background: #f4f2fd;
  padding: 2rem;
  border-radius: 12px;
  max-width: 960px;
  margin: auto;
}
.case-details:has(.a4-layout) {
  max-width: none;
  padding: 0;
}
.case-details:has(.a4-layout) .report-actions {
  width: 210mm;
  margin: 10mm auto 1rem auto;
  padding: 0;
}

h2 {
  text-align: center;
  margin-bottom: 1.5rem;
  font-size: 1.65rem;
  color: #12141a;
}

/* ==========================================================================
   A4 REPORT MODE STYLESHEET (Aligning layout cleanly without borders)
   ========================================================================== */
.a4-layout {
  width: 210mm;
  min-height: 297mm;
  margin: 10mm auto;
  padding: 20mm 25mm; /* Professional layout padding */
  background: white;
  box-sizing: border-box;
  box-shadow: 0 4px 15px rgba(0,0,0,0.1);
  font-family: 'Arial', 'Helvetica Neue', Helvetica, sans-serif;
  color: #333;
}

/* Header Info Elements */
.report-header {
  margin-bottom: 2rem;
}
.report-meta-top {
  display: flex;
  justify-content: flex-end;
  gap: 1.5rem;
  font-size: 0.9rem;
  font-weight: bold;
}
.meta-status {
  color: #333;
}
.meta-risk {
  text-transform: uppercase;
}
.meta-risk.risk-1 { color: #ef4444; }
.meta-risk.risk-2 { color: #d97706; }
.meta-risk.risk-3 { color: #2563eb; }

.school-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: #1e3a8a; /* Deep blue title matching image text color */
  margin: 0.5rem 0 0.2rem 0;
}
.school-address {
  font-size: 0.85rem;
  color: #555;
  line-height: 1.4;
  margin: 0;
}
.header-divider {
  border: none;
  border-top: 1px solid #777;
  margin: 0.8rem 0 1.5rem 0;
}

.a4-layout h2 {
  font-size: 1.25rem;
  text-align: left;
  margin-bottom: 1.8rem;
  text-transform: capitalize;
  font-weight: 700;
}

/* Document Hierarchy & Section Structure */
.report-document-layout {
  display: flex;
  flex-direction: column;
  gap: 1.75rem;
}
.section-title {
  font-size: 0.95rem;
  font-weight: bold;
  color: #000;
  border-bottom: 1px solid #ccc;
  padding-bottom: 4px;
  margin: 0 0 0.8rem 0;
}

/* Clean border-free Document Row / Grid Structure */
.doc-grid {
  display: grid;
  gap: 0.6rem 2.5rem;
}
.doc-grid.cols-2 {
  grid-template-columns: 1fr 1fr;
}
.data-cell {
  display: flex;
  align-items: baseline;
  font-size: 0.9rem;
  line-height: 1.4;
}
.data-cell .label {
  font-weight: bold;
  color: #111;
  width: 110px; /* Fixed alignment fallback */
  flex-shrink: 0;
}
.data-cell .val {
  color: #444;
}
.full-width {
  display: flex !important;
  width: 100%;
}
.full-width .label {
  width: 110px;
}

/* Document text details and body fields */
.data-block {
  font-size: 0.9rem;
}
.data-block .label {
  font-weight: bold;
  color: #111;
}
.report-text-block {
  color: #333;
  line-height: 1.6;
  text-align: justify;
  white-space: pre-wrap;
  word-break: break-word;
}
.doc-block-clean .label {
  font-weight: bold;
  color: #111;
  font-size: 0.9rem;
}
.privacy-label-clean {
  display: flex !important;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.9rem;
  font-weight: normal !important;
  color: #333 !important;
  margin: 0.4rem 0 0 0 !important;
}
.doc-checkbox {
  transform: scale(1.05);
}

/* Helper Cleaners */
.pb-1 { padding-bottom: 0.25rem; }
.mb-2 { margin-bottom: 0.5rem; }
.mb-3 { margin-bottom: 0.75rem; }
.mt-1 { margin-top: 0.25rem; }
.mt-3 { margin-top: 1rem; }
.mt-4 { margin-top: 1.25rem; }


/* ==========================================================================
   STANDARD BASE APP STYLES (Kept for UI/Tab elements alignment)
   ========================================================================== */
.header-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 2rem;
}
.status-info {
  display: flex;
  align-items: center;
  gap: 1rem;
}
.link {
  text-decoration: underline;
  color: #0a2d80;
  cursor: pointer;
}
.share-with {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin: 1rem 0;
  flex-wrap: wrap;
}
.share-chip {
  background: #f2f2f2;
  padding: 6px 12px;
  border-radius: 20px;
  font-size: 0.85rem;
}
.info-row {
  display: flex;
  justify-content: space-between;
  gap: 2rem;
  margin-bottom: 1.5rem;
}
.info-row > div {
  flex: 1;
}
.severity-tags {
  display: flex;
  gap: 0.75rem;
  margin-top: 0.5rem;
}
.severity {
  padding: 6px 16px;
  border-radius: 20px;
  background-color: #d1d1d1;
  color: #444;
  font-weight: 600;
  font-size: 0.85rem;
}
.severity.active {
  background-color: #ffb800;
  color: #fff;
}
.spec-tags {
  margin-top: 0.5rem;
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
}
.spec-chip {
  background: #f1f1f1;
  padding: 6px 14px;
  border-radius: 16px;
  font-size: 0.85rem;
  color: #333;
}
.reason-box {
  width: 100%;
  border: 1px solid #ccc;
  border-radius: 8px;
  padding: 1rem;
  font-size: 0.9rem;
  resize: none;
  background: #fafafa;
  color: #333;
}
.tabs {
  display: flex;
  border-bottom: 2px solid #ccc;
  margin-top: 1rem;
}
.tab {
  padding: 0.75rem 1.5rem;
  cursor: pointer;
  border: none;
  background: transparent;
  font-weight: bold;
  color: #333;
  border-bottom: 3px solid transparent;
  transition: 0.2s;
}
.tab.active {
  border-bottom: 3px solid #0a2d80;
  color: #0a2d80;
}
.tab-content {
  margin-top: 1.5rem;
}
.pill {
  padding: 4px 12px;
  border-radius: 20px;
  background: #eee;
  font-size: 0.85rem;
  font-weight: 500;
}

/* Action controls and UI features */
.report-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin: 0 auto 1rem auto;
  width: 100%;
  max-width: 960px;
  padding: 0 0.5rem;
}
.print-btn {
  background-color: #0a2d80;
  color: white;
  border: none;
  font-size: 14px;
  padding: .5rem 1rem;
  border-radius: 999px;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  gap: 0.25rem;
  align-items: center;
}
.report-btn {
  background-color: white;
  border: 1px solid #ccc;
  font-size: 14px;
  padding: .5rem 1rem;
  border-radius: 999px;
  cursor: pointer;
  font-weight: 600;
}
.case-type-chip {
  padding: 6px 16px;
  border-radius: 20px;
  background-color: #e5e7eb;
  color: #9ca3af;
  font-weight: 600;
}
.case-type-chip.active {
  background-color: #0a2d80;
  color: #fff;
}
.status-pill {
  padding: 0.4rem 1rem;
  border-radius: 25px;
  font-weight: bold;
}
.status-in-progress { background-color: #d1fae5; color: #065f46; border: 1px solid #065f46; }
.status-on-hold { background-color: #fce8e6; color: #b20000; border: 1px solid #b20000; }
.status-resolved { background-color: #dbeafe; color: #1e3a8a; border: 1px solid #1e3a8a; }

.media-grid-wrapper {
  margin-top: 0.5rem;
}
.media-grid {
  display: flex;
  gap: 0.75rem;
  flex-wrap: wrap;
}
.media-preview {
  width: 100px;
  height: 100px;
  object-fit: cover;
  border-radius: 6px;
}

/* Modals / Toasts definitions */
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 900;
}
.status-modal {
  background: white;
  border-radius: 12px;
  padding: 2rem;
  width: 100%;
  max-width: 480px;
}
.form-group { margin-bottom: 1.25rem; }
.form-select, .form-input, .form-textarea {
  width: 100%;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  padding: 0.5rem 0.75rem;
  box-sizing: border-box;
}
.modal-actions { display: flex; justify-content: flex-end; gap: 0.75rem; }
.btn-cancel { background-color: white; border: 1px solid #d1d5db; padding: 0.5rem 1.25rem; border-radius: 999px; cursor: pointer; }
.btn-submit { background-color: #0a2d80; color: white; border: none; padding: 0.5rem 1.25rem; border-radius: 999px; cursor: pointer; }

.toast {
  position: fixed;
  top: 20px;
  right: 0;
  transform: translateX(-50%);
  padding: 0.5rem 1rem; 
  border-radius: 0.75rem;
  color: white;
  z-index: 1000;
  width: 352px;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}
.toast-success { background-color: #e3f9e1; color: #4BB543; }
.toast-error { background-color: #fbdbdb; color: #FF3333; }

/* ==========================================================================
   PRINT ENGINE STYLES OVERRIDE
   ========================================================================== */
@media print {
  body * {
    visibility: hidden;
  }
  .case-details.a4-layout,
  .case-details.a4-layout * {
    visibility: visible;
  }
  .case-details {
    padding: 0;
    background: white;
    top: 0;
    left: 0;
    position: absolute;
    width: 100%;
  }
  .a4-layout {
    width: 100%;
    margin: 0;
    padding: 0mm; /* Printer native safe margin controls padding */
    box-shadow: none;
    border: none;
  }
  .no-print {
    display: none !important;
  }
}
</style>